### ISSUE TITLE
Backtrader Strategies

### ISSUE THREAD

**Issue by neilsmurphy** [hackingthemarkets/tradekit#14]
I notice you don't have any backtrader strategies in the backtrader folder. Are you open to having some added? If so I can put some in.  I have a lot of experience with this library.

**Comment by neilsmurphy** [comment]
Now that I look closer I can see most of the files are just place holders. I'll close this now.

**Comment by eervin123** [comment]
@neilsmurphy I don't want to speak for Larry, @hackingthemarkets, but I have watched his videos  pretty religiously for some time, and know that sometimes he will throw things out there to see if they stick. Then he might get distracted or more interested in a new or different line of thought. This may be the case here. I would assume that he would welcome it if his audience took the torch and started working on improving some of his repos. I do know in this video he mentioned that might be the case. Tbh, I'm not sure how often he checks this Github account for posts. I'll ping him and ask him to chime in.

**Comment by neilsmurphy** [comment]
@eervin123
Actually I noticed that there were many areas with place file placeholders and then closed the issue. 

No need to bother about adding more files, I was a bit premature. Appreciate your thoughts though.  

And after all, he is part time... 
Thanks.
